#%RAML 0.8
title: IBM Watson Alchemy Language API
version: "v1"
mediaType: application/json
documentation:
  - title: IBM Watson Alchemy Language API
    content: https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/
     
baseUri:  https://gateway-a.watsonplatform.net/calls
protocols: [HTTPS]


/text/TextGetLanguage:
  get:
    queryParameters:
      apikey:
        type: string
        required: true
        description:   Your API key
        example: 876701e415d654b189bf608ceb4864eda644a53f
      text:
        type: string
        required: true
        description:  Text content (must be URL encoded)
        example: My Content to be analyzed.
      outputMode:
        type: string
        required: false
        description:  json or xml (default)
        enum: [ json, xml ]
        example: json
      jsonp:
        type: string
        required: false
        description:  JSONP callback (requires outputMode to be set to json), https://en.wikipedia.org/wiki/JSONP
        example: parseResponse
      url:
        type: string
        required: false
        description:  Input here will appear as the url value in the response.
        example: My URL
      showSourceText:
        type: string
        required: false
        description:  Set this to 1 to include the source text in the response
        example: 1
         
    responses:
      200:
        description: OK - Success
        body:
          application/json:
            example : |
                                  {
                                    "status": "OK",
                                    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
                                    "url": "http://www.ibm.com/us-en/",
                                    "language": "english",
                                    "iso-639-1": "en",
                                    "iso-639-2": "eng",
                                    "iso-639-3": "eng",
                                    "ethnologue": "http://www.ethnologue.com/show_language.asp?code=eng",
                                    "native-speakers": "309-400 million",
                                    "wikipedia": "http://en.wikipedia.org/wiki/English_language"
                                  }
        

